# Generated by Django 2.1.2 on 2018-11-15 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('major', models.CharField(max_length=128)),
                ('difficulty', models.CharField(max_length=128)),
                ('skills', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('course_set', models.ManyToManyField(to='students.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rating', models.IntegerField(null=True)),
                ('course_set', models.ManyToManyField(to='students.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('major', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('course_set', models.ManyToManyField(to='students.Course')),
                ('department_set', models.ManyToManyField(to='students.Department')),
            ],
        ),
    ]
