# Generated by Django 2.1.2 on 2018-11-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='course_set',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='course_set',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course_set',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department_set',
            new_name='departments',
        ),
    ]
