# Generated by Django 2.1.2 on 2018-11-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_course_prereqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(to='students.Course'),
        ),
    ]
