# Generated by Django 2.1.2 on 2018-11-23 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20181122_0107'),
        ('students', '0004_auto_20181122_0119'),
    ]

    operations = [
    ]
